### ISSUE TITLE
Azure OpenAi

### ISSUE THREAD

**Issue by trekkim** [uzser/TalkToAI#1]
Hi , i like your app, i would like to ask if is possible add info how to use Azure OpenAI .

thank you

**Comment by uzser** [comment]
Hi there,

Thanks for your interest in TalkToAI and your suggestion! As it stands, the app is focused on OpenAI's GPT model, and I currently don't plan to integrate Azure OpenAI. However, this is an open-source project, so you're welcome to modify it as you see fit. [The Azure OpenAI documentation ](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions) may be a good starting point.

Best of luck and happy coding!

**Comment by uzser** [comment]
Hi there,

Thanks for your interest in TalkToAI and your suggestion! As it stands, the app is focused on OpenAI's GPT model, and I currently don't plan to integrate Azure OpenAI. However, this is an open-source project, so you're welcome to modify it as you see fit. [The Azure OpenAI documentation ](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions)may be a good starting point.

Best of luck and happy coding!
